const express = require('express');
const router = express.Router();
const adminController = require('../controllers/adminController');
const upload = require('../middleware/uploadMiddleware');
const upload2 = require('../middleware/uploadImagenes');
const loginController = require('../controllers/loginController');
const { verificarToken, verificarRol } = require('../controllers/loginController');

router.get('/clientes', verificarToken, verificarRol(['admin', 'super_admin']), adminController.getClientes);
router.post('/categorias', verificarToken, verificarRol(['admin', 'super_admin']), upload, adminController.registerCategory);
router.get('/categorias', verificarToken, verificarRol(['admin', 'super_admin']), adminController.getCategory);
router.get('/trabajos', verificarToken, verificarRol(['admin', 'super_admin']));
router.delete('/categorias/:tableId/:Id', verificarToken, verificarRol(['admin', 'super_admin']), adminController.deleteCategory);
router.get('/solicitud_profesional', verificarToken, verificarRol(['admin', 'super_admin']), adminController.getSolicitudProfesional);
router.put('/categorias/:tabla/:id', verificarToken, verificarRol(['admin', 'super_admin']), upload2.single('imgCategoria'), adminController.categoryPut);
router.post('/login', loginController.logearUsuario);
router.delete('/clientes/:id', verificarToken, verificarRol(['admin', 'super_admin']), adminController.eliminarCliente);
router.put('/clientes/:id', verificarToken, verificarRol(['admin', 'super_admin']), upload2.single('imagen'), adminController.actualizarCliente);
router.post('/clientes', verificarToken, verificarRol(['admin', 'super_admin']), upload2.single('imagen'), adminController.agregarCliente);
router.delete('/solicitud_profesional/:id', verificarToken, verificarRol(['admin', 'super_admin']), adminController.incorporarProfesional);
router.delete('/solicitud_profesional/:id/:usuario', verificarToken, verificarRol(['admin', 'super_admin']), adminController.eliminarSolicitudProfesional);
router.get('/profesionales/admin', verificarToken, verificarRol(['admin', 'super_admin']), adminController.obtenerProfesionales);
router.post('/profesionales', verificarToken, verificarRol(['admin', 'super_admin']), upload, adminController.agregarProfesional);
router.put('/profesionales/:id', verificarToken, verificarRol(['admin', 'super_admin']), upload, adminController.editarProfesional);
router.delete('/profesionales/:id', verificarToken, verificarRol(['admin', 'super_admin']), adminController.eliminarProfesional);
router.put('/trabajos/:id', verificarToken, verificarRol(['admin', 'super_admin']), adminController.editarSolicitudTrabajo);
router.post('/trabajos/admin', verificarToken, verificarRol(['admin', 'super_admin']), adminController.obtenerSolicitudesTrabajo);
router.get('/contratos', verificarToken, verificarRol(['admin', 'super_admin']), adminController.obtenerContratos);

module.exports = router;
